version:  '3.7'

services:
  server:
    container_name: server
    build:
      dockerfile: ./Dockerfile
      context: ./server
    restart: on-failure
    env_file:
      - ./server/.env
    ports:
      - "1337:1337"
    volumes:
      - ./server:/var/www/app
      - /var/www/app/node_modules
      - ./server/package.json:/var/www/app/package.json

